#include "toHTML.h"

void toHTML (GList* individuos) {
    FILE *fp;

    fp = fopen("../HTML/index.html", "w");
    if(!fp){
        fprintf(stderr,"Erro a abrir o ficheiro index para escrita.\n");
        return;
    }

    fprintf(fp,"<!DOCTYPE html>\n<html lang=\"pt\">\n<head>\n	\n	<meta charset=\"utf-8\">\n	<title>GenTree</title>\n\n	<link href=\"Layout/css/bootstrap.min.css\" rel=\"stylesheet\">\n <link href=\"Layout/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\n	<link href=\"Layout/css/style.css\" rel=\"stylesheet\">\n <link href=\"Layout/css/style-responsive.css\" rel=\"stylesheet\">\n	<link href=\"Layout/css/retina.css\" rel=\"stylesheet\">\n\n	<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"ico/apple-touch-icon-144-precomposed.png\">\n	<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"ico/apple-touch-icon-114-precomposed.png\">\n	<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"ico/apple-touch-icon-72-precomposed.png\">\n	<link rel=\"apple-touch-icon-precomposed\" href=\"ico/apple-touch-icon-57-precomposed.png\">\n	<link rel=\"shortcut icon\" href=\"ico/favicon.png\">\n\n</head>\n\n<body>\n	<div class=\"navbar\">\n		<div class=\"navbar-inner\" style=\"min-height:45px;\">\n <div class=\"container-fluid\">\n				<a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".top-nav.nav-collapse,.sidebar-nav.nav-collapse\">\n <span class=\"icon-bar\"></span>\n					<span class=\"icon-bar\"></span>\n					<span class=\"icon-bar\"></span>\n				</a>\n <a class=\"brand\" href=\"index.html\"><span style=\"font-size:25px;\"><i class=\"fa-icon-sitemap\"></i><span style=\"color:#bdea74;\"> Gen</span>Tree</span></a>\n \n				<div class=\"nav-no-collapse header-nav\">\n\n				</div>\n				\n			</div>\n		</div>\n	</div>\n	<!-- start: Header -->\n	\n	<div class=\"container-fluid\">\n		<div class=\"row-fluid\">\n			\n			<!-- start: Content -->\n			<div id=\"content\" class=\"span12\">\n");

    fprintf(fp,"</div>\n			<!-- end: Content -->\n			\n		<!-- start: Widgets Area -->\n		<div id=\"widgets-area\" class=\"span2 hidden-tablet hidden-phone\">\n \n		</div>\n		<!-- end: Widgets Area -->\n\n		<a id=\"widgets-area-button\" class=\"hidden-tablet hidden-phone open\"><i class=\"fa-icon-reorder\"></i></a>				\n	</div><!--/fluid-row-->\n				\n		<div class=\"clearfix\"></div>\n		\n		<footer>\n <p>\n				<span style=\"text-align:left;float:left\">GenTree 2013</span>\n				<span class=\"hidden-phone\" style=\"text-align:right;float:right;margin-right:20px;\">Programação de Linguagens</span>\n			</p>\n\n		</footer>\n				\n </div><!--/.fluid-container-->\n\n	<!-- start: JavaScript-->\n\n		<script src=\"Layout/js/jquery-1.9.1.min.js\"></script>\n	<script src=\"Layout/js/jquery-migrate-1.0.0.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery-ui-1.10.0.custom.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.ui.touch-punch.js\"></script>\n	\n		<script src=\"Layout/js/modernizr.js\"></script>\n	\n		<script src=\"Layout/js/bootstrap.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.cookie.js\"></script>\n	\n		<script src='Layout/js/fullcalendar.min.js'></script>\n	\n		<script src='Layout/js/jquery.dataTables.min.js'></script>\n\n		<script src=\"Layout/js/excanvas.js\"></script>\n	<script src=\"Layout/js/jquery.flot.js\"></script>\n	<script src=\"Layout/js/jquery.flot.pie.js\"></script>\n	<script src=\"Layout/js/jquery.flot.stack.js\"></script>\n	<script src=\"Layout/js/jquery.flot.resize.min.js\"></script>\n		\n		<script src=\"Layout/js/gauge.min.js\"></script>\n\n		<script src=\"Layout/js/jquery.chosen.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.uniform.min.js\"></script>\n		\n		<script src=\"Layout/js/jquery.cleditor.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.noty.js\"></script>\n	\n		<script src=\"Layout/js/jquery.elfinder.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.raty.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.iphone.toggle.js\"></script>\n	\n		<script src=\"Layout/js/jquery.uploadify-3.1.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.gritter.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.imagesloaded.js\"></script>\n	\n		<script src=\"Layout/js/jquery.masonry.min.js\"></script>\n	\n		<script src=\"Layout/js/jquery.knob.modified.js\"></script>\n	\n		<script src=\"Layout/js/jquery.sparkline.min.js\"></script>\n	\n		<script src=\"Layout/js/counter.js\"></script>\n	\n		<script src=\"Layout/js/raphael.2.1.0.min.js\"></script>\n	<script src=\"Layout/js/justgage.1.0.1.min.js\"></script>\n	\n		<script src=\"Layout/js/retina.js\"></script>\n\n		<script src=\"Layout/js/core.min.js\"></script>\n \n		<script src=\"Layout/js/charts.js\"></script>\n	\n		<script src=\"Layout/js/custom.js\"></script>\n	<!-- end: JavaScript-->\n \n</body>\n</html>\n");


    fclose(fp);

}
