.Dd 07/04/13               
.Dt GENTREE      
.Os GENTREE
.Sh NAME                 
.Nm GenTree - Language for defining genealogical data
.Sh SYNOPSIS             
.Nm gentree
<<           
input                          
.Sh DESCRIPTION          
.Nm
is a language for defining genealogical data. This language was created in order to define a simple and compact notation for representing familiar relationships, stories and events.
.Pp
This tool allows from a simple language create easily organized documents in HTML with all familiar information, for an easy consultation.
.Pp
By default the tool creates an output file named
.Ar Index.html
.          
.Pp          
.Sh EXAMPLES
.Bl -item -width -indent                
.It 
.Nm gentree input 
- Generates Index.html on current location.
.Pp
.El
.Sh SEE ALSO 
.Xr FLEX 1 , 
.Xr YACC 1 ,
.Xr GCC 1 
.Xr MAN 1